# Generated by Django 5.0.4 on 2024-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names_of_the_hacked', models.CharField(max_length=50, null=True)),
                ('virus_name', models.CharField(max_length=50, null=True)),
                ('code_of_data', models.IntegerField(null=True)),
                ('hacking_time', models.TimeField(null=True)),
            ],
        ),
    ]
