# Generated by Django 5.0.4 on 2024-05-07 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cipher_hills2",
            old_name="tableid",
            new_name="table_id",
        ),
    ]
