# Generated by Django 5.0.4 on 2024-04-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_lakedata_mountain_operator_forest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mountain',
            new_name='Mountain_Of_Algorithms',
        ),
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='AchanceToPassTheMountain',
            new_name='Chance_to_Pass',
        ),
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='KeeperoftheMountain',
            new_name='Mountain_Keeper',
        ),
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='MountainName',
            new_name='Mountain_Name',
        ),
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='Pathlength',
            new_name='Path_length',
        ),
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='TheWayofTheMountain',
            new_name='Way_of_the_Mountain',
        ),
    ]
