# Generated by Django 5.0.4 on 2024-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0002_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
