# Generated by Django 5.0.4 on 2024-04-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_rename_mountain_mountain_of_algorithms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakedata',
            name='DamageToTheLake_Percent',
        ),
    ]
