# Generated by Django 5.0.4 on 2024-04-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_remove_lakedata_damagetothelake_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='Way_of_the_Mountain',
            new_name='Way_of_Mountain',
        ),
    ]
