# Generated by Django 5.0.4 on 2024-04-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_rename_way_of_the_mountain_mountain_of_algorithms_way_of_mountain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain_of_algorithms',
            old_name='Way_of_Mountain',
            new_name='Way_of_the_Mountain',
        ),
        migrations.RemoveField(
            model_name='mountain_of_algorithms',
            name='Chance_to_Pass',
        ),
    ]
