# Generated by Django 5.0.4 on 2024-05-16 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0004_experiencepoints_pass_performance"),
        ("game_app", "0005_setup_performance_criteria"),
    ]

    operations = []
