# Generated by Django 5.0.4 on 2024-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0006_merge_20240516_1618"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log_Desrt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log", models.CharField(blank=True, max_length=255, null=True)),
                ("FileName", models.CharField(blank=True, max_length=255, null=True)),
                ("actions", models.CharField(blank=True, max_length=255, null=True)),
                ("LastUpdate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lvl11",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tunnel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tunnel_depth", models.IntegerField(blank=True, null=True)),
                (
                    "virus_infected_squad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "leader_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lvl11_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tunnel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tunnel_depth", models.IntegerField(blank=True, null=True)),
                (
                    "virus_infected_squad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "leader_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lvl12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_id", models.IntegerField(blank=True, null=True)),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                ("num_of_events", models.IntegerField(blank=True, null=True)),
                (
                    "ascii_helper",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lvl12_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_id", models.IntegerField(blank=True, null=True)),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                ("num_of_events", models.IntegerField(blank=True, null=True)),
                (
                    "ascii_helper",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
