# Generated by Django 5.0.4 on 2024-05-16 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0007_log_desrt_lvl11_lvl11_2_lvl12_lvl12_2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lvl12",
            new_name="ArchivesCity",
        ),
        migrations.RenameModel(
            old_name="Lvl12_2",
            new_name="ArchivesCity2",
        ),
        migrations.RenameModel(
            old_name="Lvl11",
            new_name="PlanetDungeons",
        ),
        migrations.RenameModel(
            old_name="Lvl11_2",
            new_name="PlanetDungeons2",
        ),
    ]
