# Generated by Django 5.0.4 on 2024-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0008_rename_lvl12_archivescity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "method_request",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("api", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "virus_file_detected",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIFields2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "method_request",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("api", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "virus_file_detected",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeCodeksRidge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "virus_codes",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instruction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "storage_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeCodeksRidge2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "virus_codes",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instruction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "storage_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabaseDepths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "database_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lvl_of_database", models.IntegerField(blank=True, null=True)),
                (
                    "virus_found",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "database_info",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabaseDepths2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "database_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lvl_of_database", models.IntegerField(blank=True, null=True)),
                (
                    "virus_found",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "database_info",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataManagementCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
                ("main_database", models.CharField(max_length=255)),
                ("legion_virus_names", models.CharField(max_length=255)),
                ("safe_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DataManagementCenter2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
                ("main_database", models.CharField(max_length=255)),
                ("legion_virus_names", models.CharField(max_length=255)),
                ("safe_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FinalShowdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knowledge_of_sql",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("virus_code", models.CharField(blank=True, max_length=50, null=True)),
                ("main_virus", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "virus_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalShowdown2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knowledge_of_sql",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("virus_code", models.CharField(blank=True, max_length=50, null=True)),
                ("main_virus", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "virus_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingClouds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "files_in_cloud",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "virus_file_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("functions", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingClouds2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "files_in_cloud",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "virus_file_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("functions", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryFactory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabrick_floor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("operator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "virus_request",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("viral_request_removed", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryFactory2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabrick_floor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("operator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "virus_request",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("viral_request_removed", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityCastle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_of_lock",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("functions", models.CharField(blank=True, max_length=255, null=True)),
                ("num_of_data", models.IntegerField(blank=True, null=True)),
                ("asiisafe", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityCastle2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_of_lock",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("functions", models.CharField(blank=True, max_length=255, null=True)),
                ("num_of_data", models.IntegerField(blank=True, null=True)),
                ("asiisafe", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
