# Generated by Django 5.0.4 on 2024-05-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0009_apifields_apifields2_codecodeksridge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuzzleTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game_app.level"
                    ),
                ),
            ],
        ),
    ]
